name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  setup-build-publish-deploy:
    name: Setup, Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@v0
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: haar-visualization

      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.3'

      - name: Build docker image
        run: docker build -t asia.gcr.io/haar-visualization/backend .

      - name: Configure docker authentication
        run: gcloud auth configure-docker -q

      - name: Push docker image to GCR
        run: docker push asia.gcr.io/haar-visualization/backend

      - name: Deploy image to Google Cloud Run
        run: |-
          gcloud run deploy backend \
            --quiet \
            --region "asia-east1" \
            --image "asia.gcr.io/haar-visualization/backend" \
            --platform "managed" \
            --port 80 \
            --allow-unauthenticated \
